name: Noon
options:
  bundleIdPrefix: com.noon
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "7.0.0"
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: "4.2.2"

targets:
  Noon:
    type: application
    platform: iOS
    sources:
      - path: Noon
        excludes:
          - "Preview Content"
      - path: "Noon/Preview Content"
    resources:
      - path: Noon/Resources
    dependencies:
      - package: GRDB
      - package: KeychainAccess
    settings:
      base:
        INFOPLIST_FILE: Noon/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        PRODUCT_BUNDLE_IDENTIFIER: com.noon.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"

  NoonTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NoonTests
    dependencies:
      - target: Noon
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
